changelogs:
  - kind: github
    dir: dist
    formats:
      - extension: asciidoc
        frontmatters: |
          ---
          title: "{{ .Changelog.Name }}"
          --
      - extension: json
        frontmatters: |
          ---
          title: "{{ .Changelog.Name }}"
          --
      - extension: markdown
        frontmatters: |
          ---
          title: "{{ .Changelog.Name }}"
          --
        indexfrontmatters: |
          ---
          title: "Custom Changelog"
          --
    spec:
      # No release
      # owner: updatecli-test
      #owner: olblak
      #repository: nocode
      owner: updatecli
      repository: udash
    
