changelogs:
  - kind: github
    dir: dist
    formats:
      - extension: asciidoc
        frontmatters: |
          ---
          title: "{{ .Changelog.Name }}"
          date: {{ .Changelog.PublishedAt }}
          ---
        indexfrontmatters: |
          ---
          title: "Index Changelog"
          ---
      - extension: json
        frontmatters: |
          ---
          title: "{{ .Changelog.Name }}"
          date: {{ .Changelog.PublishedAt }}
          ---
        indexfrontmatters: |
          ---
          title: "Index Changelog"
          ---
      - extension: markdown
        frontmatters: |
          ---
          title: "{{ .Changelog.Name }}"
          date: {{ .Changelog.PublishedAt }}
          ---
        indexfrontmatters: |
          ---
          title: "Index Changelog"
          ---
    spec:
      # No release
      # owner: updatecli-test
      #owner: olblak
      #repository: nocode
      owner: updatecli
      repository: udash
    
