name: Default Policies

valuesinline:
  scm:
    enabled: true
    email: bot@updatecli.io
    user: updatecli
    owner: updatecli
    repository: releasepost
    username: "updatecli-bot"
    branch: main

policies:
  - name: Update golangci-lint
    policy: ghcr.io/updatecli/policies/golangci-lint/githubaction:0.8.1@sha256:7fb34ae17a84641f02c3ff2aa0f8156a7108f32f21282b0070b8883c86ba6e67

  - name: Updatecli GitHub action
    policy: ghcr.io/updatecli/policies/autodiscovery/githubaction:0.4.1@sha256:869b676074f9fee7edd5d488140a12c3b09a5f8a175f12f26ea85a4f8bd0a9d1

  - name: Update Updatecli policies
    policy: ghcr.io/updatecli/policies/updatecli/autodiscovery:0.8.1@sha256:f8edda1a6cbf0d7274e2b847ede29fc4dc70dd5302ccb8575ae21b069cc0d8a0
    valuesinline:
      pipeline:
        labels:
          ecosystem: "updatecli"
          monitor: active

  - name: Update Updatecli version in GitHub action
    policy: ghcr.io/updatecli/policies/updatecli/githubaction:0.8.1@sha256:48872bbf1a09cfff32ff5ffa07086c20b40d6888c19c36048b18f84bbdad37fe
    valuesinline:
      pipeline:
        labels:
          ecosystem: "updatecli"
          monitor: active

  - name: Golang Version
    policy: ghcr.io/updatecli/policies/golang/version:0.7.1@sha256:b8590dff076dbd81ac160351e4749142f94a9ea718cc18c3c56c126067a29607

  - name: Major Golang Module update
    policy: ghcr.io/updatecli/policies/autodiscovery/golang:0.11.1@sha256:0a66e83d6d5c7a122bb2c7e28eb27a34e16aa16450979a8bc323d52a7a453739
    valuesinline:
      name: "deps(golang): Bump Major version for Golang module"
      pipelineid: "golang/gomod/major"
      groupby: all
      spec:
        versionfilter:
          kind: semver
          pattern: majoronly
        ignore:
          - modules:
              # Ignoring the following modules as they do not publish release
              github.com/shurcooL/githubv4: ""
        only:
          # This repository contains other go.sum file used for testing.
          # So we want to be sure that we only update the one at the root of the repository
          - path: "go.mod"

  - name: Minor Golang Module update
    policy: ghcr.io/updatecli/policies/autodiscovery/golang:0.11.1@sha256:0a66e83d6d5c7a122bb2c7e28eb27a34e16aa16450979a8bc323d52a7a453739
    valuesinline:
      name: "deps(golang): Bump Minor version for Golang module"
      pipelineid: "golang/gomod/minor"
      groupby: individual

      spec:
        versionfilter:
          kind: semver
          pattern: minoronly
        ignore:
          - modules:
              # Ignoring the following modules as they do not publish release
              github.com/shurcooL/githubv4: ""
        only:
          # This repository contains other go.sum file used for testing.
          # So we want to be sure that we only update the one at the root of the repository
          - path: "go.mod"

  - name: Patch Golang Module update
    policy: ghcr.io/updatecli/policies/autodiscovery/golang:0.11.1@sha256:0a66e83d6d5c7a122bb2c7e28eb27a34e16aa16450979a8bc323d52a7a453739
    valuesinline:
      name: "deps: bump patch version for Golang module"
      pipelineid: "golang/gomod/patch"

      spec:
        versionfilter:
          kind: semver
          pattern: patch
        ignore:
          - modules:
              # Ignoring the following modules as they do not publish release
              github.com/shurcooL/githubv4: ""
        only:
          # This repository contains other go.sum file used for testing.
          # So we want to be sure that we only update the one at the root of the repository
          - path: "go.mod"
